######################################################################
# Automatically generated by qmake (3.0) sam. oct. 4 18:15:59 2014
######################################################################

TEMPLATE = app
TARGET = interface
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    subwindows.h
FORMS += mainwindow.ui \
    newKnit.ui
SOURCES += main.cpp mainwindow.cpp \
    subwindows.cpp
RESOURCES += ressources.qrc
QT += widgets
